const data = {
  products: [
    {
      title: 'Nike Slim shirt',
      id: 'nike-slim-shirt',
      category: 'Shirts',
      thumbnail: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      reting: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      title: 'Adidas Fit shirt',
      id: 'adidas-fit-shirt',
      category: 'Shirts',
      thumbnail: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      reting: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      title: 'Nike Slim Pant',
      id: 'nike-slim-pant',
      category: 'Pants',
      thumbnail: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      reting: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      title: 'Adidas Fit Pant',
      id: 'adidas-fit-pant',
      category: 'Pants',
      thumbnail: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      reting: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
